version: '3.8'

volumes:
  databases_volume: 

services:
  bot:
    build: .
    container_name: twitter_ebalka
    restart: always
    volumes:
      - .:/app
      - databases_volume:/app/databases
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py
