import random

MODEL_MARKERS = [
    "onlyfans",
    "of.com",
    "fansly",
    "fans.ly",
    "justfor.fans",
    "just for fans"
    "jff",
    "j4f"
    "t.me",
    "http://t.me",
    "https://t.me",
    "content creator",
    "collabs",
    "model",
    "adult",
    "allmylinks",
    "only fans",
    "linktree",
    "linktr.ee",
    "privacy.com.br",
    "fansone.co",
    "chaturbate",
    "stripchat",
]

MANAGER_NICKNAME = [
    "t.me/ihatemylifebutiluvmoney",
    "@ihatemylifebutiluvmoney"
]

SOCIAL = [
    "TG",
    "Telegram",
   # "Snapchat"
]

MANAGER_MESSAGE = [
    f"Ready to buy your account - {random.choice(MANAGER_NICKNAME)} ({random.choice(SOCIAL)})",
    f"I can buy account - {random.choice(MANAGER_NICKNAME)} ({random.choice(SOCIAL)})",
    f"I want to buy your account - {random.choice(MANAGER_NICKNAME)} ({random.choice(SOCIAL)})",
   # f"Best RT tool - {random.choice(MANAGER_NICKNAME)} ({random.choice(SOCIAL)})",
]

##############
### Текста ###
##############
TEXT_INBOX = [
    "Okay, but you go first! 🤔",
    "You do it first, then I'll follow! 🔄",
    "Alright, but it's your turn first! 😉",
    "Okay, after you! 😏",
    "You go first, and I'll join in! 🤝",
    "Sure, but you lead the way! 👣",
    "Go ahead, I'll catch up! 🏃‍♂️",
    "You take the first step, then I'll follow! 🚶‍♀️",
    "Okay, but it's your move! 🎮",
    "Alright, you take the first shot! 🎯",
    "You go first, I'm right behind you! 🚶‍♂️",
    "Fine, but you're up first! 🔥",
    "Okay, but only if you do it first! 🏁",
    "You first, and I'll join in! 💪",
    "Sure, but after you! 🥇",
    "I'll follow your lead—first move's on you! 🎬",
    "Alright, but you start it! 🕹️",
    "Okay, but you do it first and I'll jump in! 👊",
    "You take the first step, I'll follow right away! 👣",
    "Alright, you're the one who starts! 💥",
    "You first, then I'll be right there! 👋",
    "Okay, but you're the first one up! 🚀",
    "You lead, and I'll follow! 👌",
    "Fine, but only if you go first! 💯",
    "Alright, but you're first! 🎤",
    "Okay, you take the first move! 🏆",
    "You start it, then I'll join! 🏃‍♀️",
    "Go ahead, it's your turn first! 🎮",
    "Okay, but you're the one who leads! 👑",
    "You go first, and then I'll catch up! ⚡",
    "Sure, but you take the first step! 👢",
    "Alright, you're first to go! 🌟",
    "Okay, you start, and I'll follow! 🔁",
    "You make the first move, then I'll join in! 💥",
    "Fine, but you're first in line! 🏅",
    "You go first, and I’ll follow right behind! 🏃‍♂️",
    "Alright, you lead the way! 🛤️",
    "You do it first, and I'll be next! 🏁",
    "Okay, but you're up first! 🏆",
    "Sure, but only if you start it! 🎬",
    "You go first, and I’ll catch up! 🔥",
    "Alright, you’re the first to move! 💨",
    "Fine, but you go first! 💥",
    "Okay, but you're the first one to act! 💪",
    "You do it first, and I’ll follow! 🎯",
    "You go first, I’ll be right there! 👌",
    "Okay, but after you start! 🎬",
    "Alright, you lead the charge! ⚡",
    "You take the first step, then I’ll follow! 👟",
    "Sure, but you're first to go! 🚀",
    "You take the first move, and I'll be right behind! 🏅",
    "Okay, but you go ahead first! 🏁",
    "You lead, I’ll follow right away! 🏃‍♀️",
    "Fine, you go first, then I’ll follow! 🏆"
]
TEXT_PINNED = [
    "📌 If the link won't open, retweet my pinned post! 🔁",
    "🚨 Can't open it? Retweet my pinned post! 📌",
    "🔒 Link not accessible? Retweet the pinned post! 🔄",
    "❗Can't access? Retweet my pinned post! 🔁",
    "📍 If it's unavailable, retweet my pinned post! 🌐",
    "⚠️ Link not working? Retweet the pinned post! 🔄",
    "🚫 Can't open it? Try retweeting my pinned post! 📌",
    "🔑 Link not available? Retweet the pinned post! 🔁",
    "💡 If the link isn't working, retweet my pinned post! 📌",
    "🌐 Can't access it? Retweet the pinned! 🔄",
    "📌 Link not working? Retweet the pinned post! 🔁",
    "❗ Link unavailable? Retweet the pinned post to open it! 🔄",
    "🔁 Retweet the pinned post if the link won't open! 📌",
    "⚡ Link not working? Retweet the pinned post! 📌",
    "📍 If it's not working, retweet the pinned post! 🔁",
    "🛠️ Link unavailable? Retweet the pinned post! 🔄",
    "📌 Can't open it? Retweet the pinned post! 🔁",
    "🔗 If the link won't open, retweet the pinned post! 📌",
    "🔁 Retweet my pinned post if the link isn't working! 📌"
]
TEXT_DONT_FAKE = [
    "⛔ Fake = Ban! Don't try it! 🚫",
    "⚠️ Fake content? That's a ban! ⛔",
    "⛔ Fake = Ban, no exceptions! 🚫",
    "🚨 Fake? Instant ban! 🛑",
    "🚫 Fake behavior = Ban! ⚠️",
    "⛔ Fake is banned here! 🚷",
    "⚠️ Don’t fake it, or you're banned! 🚫",
    "❌ Fake = Ban. Simple as that! ⛔",
    "🚫 Fake accounts = Ban. Keep it real! 💯",
    "🚨 Fake = Ban, no tolerance! ⛔",
    "⛔ If it's fake, you’re banned! 🛑",
    "⚠️ Fake = Ban. Don’t risk it! ❌",
    "🚫 Faking leads straight to a ban! ⛔",
    "⛔ No fake RTs allowed! 🚫",
    "⚠️ Fake = Ban. Zero tolerance! 🛑",
    "⛔ Fake will get you banned! 🚫",
    "❌ Fake = Ban, don’t try it! 🚫",
    "⚠️ Fake is a one-way ticket to ban! ⛔",
    "⛔ Fake = Ban. Play fair! ⚖️",
    "🚫 Fake? Prepare for a ban! ⛔",
    "🚨 Fake = Ban. No exceptions! ⚠️",
    "⛔ Fake equals banishment! 🚫",
    "⚠️ Fake? You’re banned! 🛑",
    "❌ Fake = Ban, simple and clear! ⛔",
    "🚫 No fakes here! Ban incoming! 🚷",
    "⛔ Fake = Instant ban! 🚫",
    "⚠️ Fake = Ban. Don’t cross the line! 🚫",
    "🚨 Fake content = Ban! 🚫",
    "⛔ Fake = Automatic ban! ❌",
    "🚫 Fake behavior? Instant ban! ⚠️",
    "⛔ Don’t fake it, or you’re banned! 🚫",
    "🚨 Fake RT = Ban. No warning! ⛔",
    "⚠️ Fake = Ban. No second chances! ❌",
    "⛔ Fake? You’re banned! 🚷",
    "🚫 Fake content = Banishment! ⛔",
    "⚠️ Fake = Ban, that’s the rule! 🚫",
    "🚷 Fake = Ban. Simple as that! ⛔",
    "⛔ Fake = Ban, take it seriously! 🚫",
    "❌ Fake = Ban, no excuses! 🚫",
    "🚨 Fake = Ban. No fakes allowed! ⛔",
    "⚠️ Fake content = Ban, keep it real! 🛑",
    "⛔ Fake? You’re getting banned! 🚫",
    "🚫 Fake = Ban. Play by the rules! ⛔",
    "⛔ Fake = Ban, don’t try to cheat! 🚫",
    "⚠️ Fake behavior will get you banned! 🚫",
    "🚷 Fake? Ban incoming! ⛔"
]
TEXT_FOR_NEW = [
    "Hello! 👋 Retweet for Retweet? 🔄",
    "Hey there! 😊 R for R? 🔄",
    "Hello! 👋 How about a Retweet for Retweet? 🔄",
    "Hi! 🙋‍♂️ RT for RT? 🔄",
    "Hey! 😎 R ↔ R? 🔄",
    "Hello! 👋 Retweet exchange? 🔄",
    "Hey! ✨ RTxRT? Let's do it! 🔄",
    "Hello! 👋 R for R exchange? 🔄",
    "Hi there! 👋 Retweet for Retweet? 🔄",
    "Hello! 🙋‍♂️ RT ↔ RT? 🔄",
    "Hey! 🤗 R for R? Retweet for Retweet! 🔄",
    "Hi! 👋 Retweet swap? 🔄",
    "Hey! 🔄 RTxRT? Time for it! 🔄",
    "Hello! 😊 R ↔ R? Let's go! 🔄",
    "Hey there! 👋 RT for RT? 🔄",
    "Hi! 🙋‍♂️ RT ↔ RT exchange? 🔄",
    "Hello! 🤝 Retweet swap for a Retweet? 🔄",
    "Hey! 🔄 R for R trade? 🔄",
    "Hello! 👋 RT ↔ RT exchange? 🔄",
    "Hi! 😎 Retweet for Retweet? 🔄",
    "Hello! 🤝 R ↔ R? Retweet back? 🔄",
    "Hey! 🔄 RTxRT exchange? 🔄",
    "Hi! ✨ Retweet trade? 🔄",
    "Hello! 👋 R ↔ R exchange? 🔄",
    "Hey! 😊 RT for RT swap? 🔄",
    "Hi there! 👋 Retweet exchange? 🔄",
    "Hello! 🤝 R ↔ R back? 🔄",
    "Hey! ✨ RT ↔ RT? Let’s do it! 🔄",
    "Hi! 🙋‍♂️ Retweet for Retweet trade? 🔄",
    "Hello! 🔄 RTxRT swap? 🔄",
    "Hey! 😎 R for R swap? 🔄",
    "Hello! 👋 RT ↔ RT exchange? 🔄",
    "Hi! 😎 R ↔ R trade? 🔄",
    "Hey! 😊 RTxRT back? 🔄",
    "Hello! 🤝 R ↔ R for RT? 🔄",
    "Hi there! 👋 RT for RT exchange? 🔄",
    "Hey! ✨ RTxRT swap? 🔄",
    "Hello! 👋 Retweet swap? 🔄",
    "Hi! 🙋‍♂️ RT ↔ RT exchange? 🔄",
    "Hey! 🤝 R ↔ R exchange? 🔄",
    "Hello! 🔄 RTxRT back? 🔄",
    "Hey there! 👋 Retweet for Retweet? 🔄",
    "Hi! 😊 RT ↔ RT swap? 🔄",
    "Hello! 🤝 Retweet exchange? 🔄",
    "Hey! 😎 R for R exchange? 🔄",
    "Hi! 🙋‍♂️ RT ↔ RT trade? 🔄",
    "Hello! 👋 R for R? Retweet for Retweet? 🔄"
]
TEXT_FOR_EXIST = [
    "Done! ✔️ RT for RT again? 🔄",
    "All set! ✅ R for R again? 🔄",
    "Done! ✅ Ready for RTxRT again? 🔄",
    "Mission accomplished! ✔️ RT ↔ RT again? 🔄",
    "Done! ✔️ How about RT for RT again? 🔄",
    "Completed! ✅ R ↔ R once more? 🔄",
    "Done! ✅ Another RTxRT? 🔄",
    "All done! ✔️ Ready for round two of RTxRT? 🔄",
    "Done! ✅ RT ↔ RT again? Let's go! 🔄",
    "All set! ✅ R for R again? 🔄",
    "Mission complete! ✔️ RTxRT once more? 🔄",
    "Done! ✅ Another RT for RT? 🔄",
    "Completed! ✔️ RTxRT again? 🔄",
    "Done! ✅ Ready for RT ↔ RT again? 🔄",
    "All done! ✔️ Let's do another RTxRT! 🔄",
    "Done! ✅ R ↔ R again? 🔄",
    "Mission accomplished! ✔️ RT for RT again? 🔄",
    "Done! ✅ RTxRT again? 🔄",
    "All set! ✔️ RT for RT again? 🔄",
    "Done! ✅ Let's go for another RT ↔ RT! 🔄",
    "Completed! ✅ RTxRT once again? 🔄",
    "Done! ✔️ R for R, again? 🔄",
    "Done! ✅ Ready for another RTxRT? 🔄",
    "All done! ✔️ R ↔ R again? 🔄",
    "Done! ✅ Let's do it again—RTxRT! 🔄",
    "Completed! ✅ RT for RT again? 🔄",
    "Done! ✔️ How about another RT ↔ RT? 🔄",
    "All set! ✅ Ready for another RT for RT? 🔄",
    "Done! ✅ RTxRT again? 🔄",
    "Mission complete! ✔️ R for R again? 🔄",
    "Done! ✅ Another round of RT ↔ RT? 🔄",
    "All done! ✔️ RTxRT once more? 🔄",
    "Done! ✅ Ready for RT for RT again? 🔄",
    "Completed! ✔️ RT ↔ RT again? 🔄",
    "Done! ✅ Let's go again—RTxRT! 🔄",
    "All set! ✔️ Another RT for RT? 🔄",
    "Mission accomplished! ✅ RTxRT again? 🔄",
    "Done! ✔️ How about RT ↔ RT again? 🔄",
    "Completed! ✅ Ready for RTxRT again? 🔄",
    "Done! ✅ R ↔ R again? 🔄",
    "All done! ✔️ Ready for RT ↔ RT again? 🔄",
    "Done! ✅ RTxRT again? Let's do it! 🔄"
]
TEXT_FOR_NOT_FOUND = [
    "Sorry, I didn't find the tweet in your message/pinned. Please send it again! 🔄",
    "Oops, no tweet found in your message/pinned. Could you resend it? 📨",
    "Sorry, I couldn't find your tweet. Please send it again! 🔄",
    "No tweet in your message/pinned. Please send it again! 📝",
    "Apologies, but I didn't find a tweet. Kindly resend! 🔄",
    "I couldn't find the tweet in your message/pinned. Can you send it again? 💬",
    "Oops! No tweet detected. Could you please resend it? 🔄",
    "Sorry, I didn't find any tweet. Could you send it again? 📝",
    "I couldn't find the tweet in your pinned/message. Please resend! 📨",
    "Sorry, I couldn't find your tweet. Kindly send it again! 🔄",
    "No tweet found in your message/pinned. Please send it again! 🔁",
    "Apologies, but no tweet was found. Please resend it! 🔄",
    "I couldn't find the tweet in your message. Kindly resend! 📨",
    "Sorry, no tweet found. Please send it again! 🔁",
    "Oops, no tweet in your message/pinned. Please resend! 📝",
    "I didn't find the tweet. Could you send it again, please? 🔄",
    "Sorry, but no tweet was found in your message/pinned. Please resend! 📲",
    "No tweet found in your message/pinned. Kindly send it again! 🔄",
    "I couldn't find the tweet in your pinned message. Can you send it again? 📨",
    "Sorry, I couldn't find a tweet in your message/pinned. Please resend! 🔄",
    "Oops, no tweet in the message/pinned. Could you resend it? 📝",
    "Sorry, no tweet found in your message/pinned. Please send it again! 🔄",
    "I didn't find the tweet in your pinned/message. Kindly resend it! 📲",
    "Sorry, I couldn't find a tweet. Please send it again! 🔁",
    "Oops! No tweet found. Kindly send it again! 🔄",
    "Sorry, I didn't find the tweet. Please send it again! 📩",
    "No tweet found in your message. Could you resend it? 📝",
    "I couldn't find your tweet in the message/pinned. Please send it again! 🔄",
    "Sorry, no tweet was found. Kindly send it again! 🔁",
    "Apologies, I couldn't find the tweet. Please resend! 📨",
    "Oops, no tweet in your pinned/message. Please send it again! 📲",
    "Sorry, no tweet found in your message. Please resend! 🔄",
    "I couldn't find a tweet in your message/pinned. Kindly resend it! 🔄",
    "Sorry, I didn’t find any tweet in your message/pinned. Please send it again! 🔁",
    "No tweet found. Could you kindly send it again? 📲",
    "Sorry, no tweet in your message/pinned. Could you send it again, please? 🔄",
    "Oops, no tweet detected. Please send it again! 🔄",
    "Sorry, I couldn’t find the tweet. Kindly resend! 📝",
    "No tweet found in your pinned/message. Could you send it again? 🔄",
    "Apologies, I didn’t find the tweet. Could you resend it? 🔄",
    "I couldn't find the tweet in your pinned message. Please send it again! 📨",
    "Sorry, I couldn't find your tweet. Please send it again! 🔁",
    "Oops, no tweet in your message. Kindly resend it! 📲",
    "Sorry, I couldn't find a tweet. Could you please send it again? 🔄",
    "No tweet found in your pinned message. Kindly resend it! 📝"
]
TEXT_IF_DID_PINNED = [
    "Link is not working! I did your pinned! 📌",
    "Sorry, the link isn't working! I’ve done your pinned! 🔄",
    "Link not working! Don’t worry, I did your pinned! 📌",
    "Link issue! I’ve pinned it for you! 📌",
    "The link isn’t working! I’ve done your pinned instead! 📌",
    "Link not available! I’ve pinned your post for you! 📌",
    "Oops, link isn’t working! I’ve done your pinned! 🔄",
    "The link isn’t working, but I’ve pinned it for you! 📌",
    "Link not functional! I’ve pinned it for you! 📌",
    "Link is broken! I’ve done your pinned for you! 📌",
    "Link is not working! I’ve pinned your post! 📌",
    "The link failed! But I’ve pinned it for you! 📌",
    "Link not found! No worries, I’ve done your pinned! 📌",
    "Link issue! I’ve done your pinned instead! 📌",
    "Sorry, the link isn’t working! I’ve pinned your content! 📌",
    "Link not working! But I’ve pinned your post! 📌",
    "Link failed! Don’t worry, I’ve pinned it! 📌",
    "Link is broken! But I’ve done your pinned! 📌",
    "Link not functional! I’ve pinned it for you! 📌",
    "The link isn’t working! I’ve done your pinned for you! 📌",
    "Link not working! I’ve pinned it for you! 📌",
    "Link error! I did your pinned! 📌",
    "Link is down! But I’ve pinned it! 📌",
    "Link is not available! I’ve pinned your post for you! 📌",
    "Link not working! But no worries, I’ve pinned it! 📌",
    "Link failed! I’ve pinned your post for you! 📌"
]
WARNING_TEXT = [
    "I couldn't find YOUR retweet. 1/2 warning ⚠️ One more time = ban 🚫",
    "Where is YOUR retweet? 1/2 warning 🚨 Next time - banned 🔒",
    "YOUR retweet is missing. First warning ⚡ Second time = block 🚫",
    "Can't locate YOUR retweet. First half of warning 🛑 Repeat = ban 🔇",
    "YOUR retweet not found. 1/2 warning 🚧 Another miss - blocked 🚨",
    "I don't see YOUR retweet. 1/2 warning ⚠️ Next attempt = ban 🔒",
    "YOUR retweet is absent. First warning 🚨 Second time = full block 🚫",
    "Couldn't verify YOUR retweet. 1/2 warning 🛑 Repetition = banned 🔇",
    "Where exactly is YOUR retweet? First half warning ⚠️ Again = block 🚨",
    "YOUR retweet is invisible. 1/2 warning 🚧 Next time we block 🔒",
    "No sign of YOUR retweet. First warning 🚨 Second attempt = ban 🚫",
    "YOUR retweet is nowhere. 1/2 warning ⚠️ Repeat = blocked 🔇",
    "Cannot find YOUR retweet. First half warning 🛑 Once more = ban 🚨",
    "YOUR retweet is missing in action. 1/2 warning 🚧 Next = block 🔒",
    "Show me YOUR retweet. 1/2 warning ⚠️ Repetition = banned 🚫",
    "YOUR retweet not confirmed. First warning 🚨 Second time = block 🔇",
    "I'm not seeing YOUR retweet. 1/2 warning 🛑 Another step = ban 🚨",
    "YOUR retweet is absent. First half warning ⚠️ Repeat = blocked 🚫",
    "Where's YOUR retweet? 1/2 warning 🚧 Next time - block 🔒",
    "YOUR retweet cannot be located. First warning 🚨 Second case = ban 🔇",
    "No retweet from YOU. 1/2 warning ⚠️ Again = block 🚫",
    "YOUR retweet is completely missing. First half warning 🛑 Repeat = ban 🚨",
    "Waiting for YOUR retweet. 1/2 warning 🚧 Next time we block 🔒",
    "YOUR retweet is not verified. 1/2 warning ⚠️ Second time = ban 🚫",
    "Cannot validate YOUR retweet. First warning 🚨 Repeat = blocked 🔇",
    "YOUR retweet is nowhere found. 1/2 warning 🛑 Another chance = ban 🚨",
    "Still no retweet from YOU. First half warning ⚠️ Second case = block 🚫",
    "YOUR retweet location: unknown. 1/2 warning 🚧 Next time - ban 🔒",
    "Retweet by YOU: not detected. First warning 🚨 Repeat = block 🔇",
    "Missing YOUR retweet confirmation. 1/2 warning ⚠️ Again = banned 🚫",
    "YOUR retweet status: not found. First half warning 🛑 Second time = ban 🚨",
    "Searching for YOUR retweet. 1/2 warning 🚧 Next step - block 🔒",
    "YOUR retweet is not here. First warning ⚠️ Repetition = ban 🚫",
    "I can't spot YOUR retweet. 1/2 warning 🚨 Another miss = blocked 🔇",
    "YOUR retweet is absent. First half warning 🛑 Second case = ban 🚫",
    "Looking for YOUR retweet. 1/2 warning ⚠️ Next time - block 🚨",
    "YOUR retweet remains unconfirmed. 1/2 warning 🚧 Repeat = ban 🔒",
    "Cannot track YOUR retweet. First warning 🚨 Again = blocked 🔇",
    "YOUR retweet is completely invisible. 1/2 warning 🛑 Second case = ban 🚫",
    "Expecting YOUR retweet. First half warning ⚠️ Next time - block 🚨",
    "YOUR retweet is not visible. 1/2 warning 🚧 Repetition = ban 🔒",
    "No confirmation of YOUR retweet. First warning 🚨 Again = blocked 🔇",
    "YOUR retweet location: zero. 1/2 warning 🛑 Second case = ban 🚫",
    "Seeking YOUR retweet. First half warning ⚠️ Next time - ban 🚨",
    "YOUR retweet: not found. 1/2 warning 🚧 Repeat = block 🔒",
    "Verifying YOUR retweet: failed. First warning 🚨 Another miss = banned 🔇",
    "Tracking YOUR retweet: unsuccessful. 1/2 warning 🛑 Second attempt = ban 🚫"
]
FAKER_BLOCK_TEXT = [
    "You are blocked because you are a faker 🚫🤥",
    "Blocked for being a total faker 🔒🎭",
    "Fake activity detected. Blocked. 🚨🤡",
    "Your faker status has been confirmed. Blocked. 🛑😒",
    "Caught in the act of faking. Goodbye. 🚫👋",
    "You're blocked for pure fakery 🔇🤨",
    "Faker alert: Account suspended 🚨🚫",
    "Blocking you for your fake behavior 🛑🤥",
    "Detected: 100% faker. Action taken. 🚫🕵️",
    "Fake profile identified. Blocked. 🔒🚨",
    "Your faker credentials are impressive. Blocked. 😏🚫",
    "No real activity. Pure faker. Blocked. 🛑🤡",
    "Faker status: Confirmed. Account blocked. 🚨🔇",
    "Your fakeness has reached legendary levels. Blocked. 🚫😂",
    "Blocking a professional faker. Congratulations. 🔒🏆",
    "Faker detected. System response: Block. 🚨🤖",
    "Too much fake. Not tolerated. Blocked. 🛑🚫",
    "Your faker skills are not welcome here 🔇🚨",
    "Confirmed faker. Immediate block initiated. 🚫🛑",
    "Level of fakery: Maximum. Blocked. 🔒😒",
    "Faker algorithm triggered. Blocking in progress. 🚨🤖",
    "Your fake profile is now inactive 🚫🔇",
    "Blocking due to extreme fakery 🛑🤥",
    "Faker status update: Blocked 🚨🚫",
    "Detected: Professional faker. Action taken. 🔒🕵️",
    "Your fakeness has consequences. Blocked. 🚫😤",
    "Faker protocol activated. Blocking complete. 🛑🤡",
    "No real content. Pure faker. Blocked. 🚨🔇",
    "Impressive faker skills. Blocked accordingly. 🚫😏",
    "Fake activity flagged. Account blocked. 🔒🚨",
    "Your faker reputation precedes you. Blocked. 🛑🤥",
    "Maximum faker tolerance reached. Blocking now. 🚫🚨",
    "Faker identification: Successful. Block initiated. 🔇🤖",
    "Too much fake. Not allowed. Blocked. 🚫😒",
    "Your faker status is now official. Blocked. 🛑🚨",
    "Blocking a world-class faker 🔒🏆",
    "Faker detected. Immediate shutdown. 🚫🤡",
    "Your fake profile ends here 🛑🔇",
    "Professional faker level: Blocked 🚨🚫",
    "Fakery beyond acceptable limits. Blocked. 🔒😤",
    "Faker algorithm says: Goodbye 🚫👋",
    "Your fake activity is now terminated 🛑🚨",
    "Blocking due to systematic fakery 🔇🤥",
    "Faker status: Permanently blocked 🚫🔒",
    "Detected: Master of fake 🚨🤡",
    "Your faker credentials revoked 🛑😒",
    "Blocking the king/queen of fake 🚫👑",
    "Faker profile neutralized 🔇🚨",
    "Your fakeness has been officially recognized 🚫🏅",
    "Final verdict: Faker. Blocked. 🛑🔒"
]

BANNED_WORDS = [
    "murder",
    "blood",
    "death",
    "dead",
    "kill",
    "rape",
    "raping",
    "pedophile",
    "pedo",
    "kid",
    "underage",
    "under age"
]